### ISSUE TITLE
Getting more than 100 results

### ISSUE THREAD

**Issue by ThisIsNoahEvans** [getlinksc/scrape_google#3]
Hello,

This code only gets results from page 1 of the search, which is an issue for me. I can add an argument to the search query URL that will list 100, but ideally I’d want every result on Google.

Is there a way that you can add this?

Thank you!

**Comment by getlinksc** [comment]
When you search you can give it a parameter `start` and which denotes the start of the results. So if I wanted results 500 to 600. I would set the `start=500`. Then you can just loop through the results and increment the start.

```python
# get results starting at 500
query = "hackernoon How To Scrape Google With Python"
query = query.replace(' ', '+')
URL = f"https://google.com/search?q={query}&start=500"
```

**Comment by ThisIsNoahEvans** [comment]
Thank you! So to get every result, I would have to run a 100 times loop for each range - e.g. loop 1 `start=100` then loop 2 `start=200`? 

Sorry if I'm being a bit slow, just wanted to check I had it right. Thanks so much for the response! :)

**Comment by getlinksc** [comment]
Yes that is correct.

After a a couple searches Google will start to blacklist your IP address. I'll leave it to your imagination to figure out a way to bypass that.

**Comment by ThisIsNoahEvans** [comment]
Thank you for your help - I'll have to think about that haha.
